base_url = "https://aksh79.github.io"
title = "aksh79"
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
minify_html = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

[link_checker]
internal_level = "warn"

[markdown]

[markdown.highlighting]
style = "inline"
theme = "ayu-dark"

[extra]
use_cdn = false
theme = "toggle"

menu = [
  { name = "/notes", url = "/infosec-garden", weight = 1 },
  { name = "/writeups", url = "/writeups", weight = 2 },
  { name = "/projects", url = "/projects", weight = 3 },
]

socials = [
  { name = "twitter", url = "https://x.com/akshayanand_7", icon = "twitter" },
  { name = "github", url = "https://github.com/aksh79/", icon = "github" },
  { name = "rss", url = "/atom.xml", icon = "rss" },
]

[extra.taxonomies]
sort_by = "name"
reverse = false

[extra.analytics]
enabled = true
